[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build" 

[project]
name = "particle-analysis"
version = "0.0.1"
authors = [
    { name="Hendrik Roch", email="roch@fias.uni-frankfurt.de" },
    { name="Nils Sass", email="nsass@fias.uni-frankfurt.de" },
]
description = "Package to analyze particle data from event generators."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
    "Natural Language :: English"
]

[project.urls]
"Homepage" = "https://github.com/Hendrik1704/particle-analysis"
"Bug Tracker" = "https://github.com/Hendrik1704/particle-analysis/issues"

dependencies = [
    "particle>=0.22.0",
]
